<nav class="navbar navbar-expand-lg menu">
	<div class="container">
	  <div class="navbar-nav">
	  	<a class="menuItem" href="/timeline">
	  		Home
	  	</a>

	  	<a class="menuItem" href="/sair">
	  		Sair
	  	</a>
			<img src="/img/twitter_logo.png" class="menuIco" />

		<a href="/perfil" class="menuItem">
			Perfil
		</a>
	  </div>
	</div>
</nav>

<div class="container">
    <div class="d-flex justify-content-center mt-5">
        <div class="row">
            <div class="d-flex justify-content-center">
                <img src="/img/twitter_logo.png" />
            </div>
        </div>
    </div>

    <div class="row mt-5">
        <?php 
            if (isset($_GET['erro'])) {
                $code = $_GET['erro'];

                switch ($code) {
                    case 'false':
                        ?>
                        <div class="alert alert-success d-flex justify-content-center">Atualização realizada com sucesso</div>
                         <?php break;
                    case 'true':
                        ?>
                        <div class="alert alert-danger d-flex justify-content-center">Erro ao Atualizar Dados</div>
                        <?php break;
                };
            }
        ?>
        <div class="col-md-8">
            <form action="/alterarperfil" method="post" enctype="multipart/form-data">
                <div class="form-group">
                    <label for="name">Nome:</label>
                    <input type="text" name="name" class="form-control" id="name" value="<?= $this->view->user->name ?>">
                </div>
                <div class="form-group">
                    <label for="email">E-mail:</label>
                    <input type="email" name="email" class="form-control" id="email" value="<?= $this->view->user->email ?>">
                </div>
                <div class="form-group">
                    <label for="password">Senha:</label>
                    <input type="password" name="password" required class="form-control" id="password" placeholder="Digite sua Nova Senha">
                </div>
                
                <button type="submit" class="btn btn-success">Salvar Alterações</button>
                    
            
        </div>

        <div class="col-md-4">
            <h4 class="d-flex justify-content-center">Foto de Perfil</h4>

            <div class="d-flex justify-content-center img-container">
                <img src="img_perfil/<?= $this->view->user->image ?>" alt="foto de perfil" class="img-perfil img-fluid">
            </div>

            <div class="form-group">
                <input type="file" name="img" id="img"> 
            </div>
            </form>  
        </div>
    </div>
        
</div>